module.exports={
    default:{
        "formatOptions":{
                "snippetInterface":"async-await",
        },
        requireModule:[
            "ts-node/register"
        ],
        require:[
            "src/test/steps/**/*.ts",
            "src/test/hooks/hooks.ts",
            "src/test/world/world.ts",
            "src/test/support/**/*.ts"
        ],
        paths:[
            "src/test/features/**/*.feature"
        ],
        publishQuiet:true,
        dryRun:false,
        format:[
            "progress-bar",
            "json:reports/Json_Report/Json-report.json",
            "html:reports/Html_Report/Html-report.html"     
        ],
        parallel:1
    }
}